version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://host.docker.internal:8000
    ports:
      - "80:80"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
